version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Group minor and patch updates together to reduce PR noise
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "@playwright/*"
          - "@tsconfig/*"
          - "typescript"
          - "ts-node"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@modelcontextprotocol/*"
          - "express"
          - "playwright"
          - "commander"
          - "dotenv"
          - "zod"
        update-types:
          - "minor"
          - "patch"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Add reviewers (you can customize these)
    reviewers:
      - "barre"  # Replace with actual GitHub username if different
    # Prefix commit messages
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"

  # Enable version updates for Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "barre"  # Replace with actual GitHub username if different
    commit-message:
      prefix: "docker"

  # Enable version updates for GitHub Actions (if you add any workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "barre"  # Replace with actual GitHub username if different
    commit-message:
      prefix: "actions" 