version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playwright-mcp
    environment:
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      # Set to 'sse' or 'http' to use HTTP/SSE transport, leave unset for stdio
      - MCP_TRANSPORT=${MCP_TRANSPORT:-sse}
      # Port for HTTP/SSE transport (only used when MCP_TRANSPORT=sse/http)
      - MCP_PORT=${MCP_PORT:-3333}
    command: ["node", "dist/mcp.js"]
    profiles:
      - mcp
    ports:
      # Expose port when using HTTP/SSE transport
      - "${MCP_PORT:-3333}:${MCP_PORT:-3333}"
    # Keep stdio settings for backward compatibility
    stdin_open: true
    tty: true 